// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "woodguy":return img`
........................
....ffffff..............
..ffeeeef2f.............
.ffeeeef222f............
.feeeffeeeef...cc.......
.ffffee2222ef.cdc.......
.fe222ffffe2fcddc.......
fffffffeeeffcddc........
ffe4444f44ecddc.........
fee4444f44ecdc..........
.feee44444dccc..........
..ffee4444dde...........
...f222244ee............
...f2222e2f.............
...f444444f.............
....ffffff..............
.....fff................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
